module.exports = {
  content: ["./index.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121414",
        "surface-dim": "#121414",
        "surface-bright": "#38393a",
        "surface-container-lowest": "#0c0f0f",
        "surface-container-low": "#1a1c1c",
        "surface-container": "#1e2020",
        "surface-container-high": "#282a2b",
        "surface-container-highest": "#333535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e2beba",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#2f3131",
        "outline": "#aa8986",
        "outline-variant": "#5a403e",
        "surface-tint": "#ffb4ac",
        "primary": "#ffb4ac",
        "on-primary": "#690007",
        "primary-container": "#b22222",
        "on-primary-container": "#ffc8c2",
        "inverse-primary": "#b52424",
        "secondary": "#c8c6c6",
        "on-secondary": "#303030",
        "secondary-container": "#474747",
        "on-secondary-container": "#b6b5b4",
        "tertiary": "#fbbc00",
        "on-tertiary": "#402d00",
        "tertiary-container": "#775700",
        "on-tertiary-container": "#ffcf66",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#92030f",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#c8c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        "tertiary-fixed": "#ffdfa0",
        "tertiary-fixed-dim": "#fbbc00",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
        "background": "#121414",
        "on-background": "#e2e2e2",
        "surface-variant": "#333535"
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1200px",
        "gutter": "20px"
      },
      fontFamily: {
        "display-lg": ["Domine", "serif"],
        "headline-lg": ["Domine", "serif"],
        "headline-lg-mobile": ["Domine", "serif"],
        "headline-md": ["Domine", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "label-lg": ["Work Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }]
      }
    }
  },
  plugins: []
};
